---
title: "README"
author: "Eduardo Pacheco"
date: "28 de agosto de 2018"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## how to clean Human Activity Recognition Using Smartphones Data Set 

We created 1 script to help pelople to clean Human Activity Recognition Using Smartphones Data Set available on http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones and help further anlaysis.

You can see the variables used in Code_Book.md or Code_Book.html

Basically the script R script called run_analysis.Rdoes the following

1.Merges the training and the test sets to create one data set.
2.Extracts only the measurements on the mean and standard deviation for each measurement.
3.Uses descriptive activity names to name the activities in the data set
4.Appropriately labels the data set with descriptive variable names.
5.From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

The output file is TIDYSET.txt

